GIT_TOP=$(shell git rev-parse --show-toplevel 2>/dev/null)
# git refuses a repo owned by another user (a folder mounted into the dev
# container, until safe.directory is set). Then the repo root is simply the
# folder above this file, which works from src/ and from src/gotty/.
ifeq ($(GIT_TOP),)
GIT_TOP := $(abspath $(dir $(realpath $(lastword $(MAKEFILE_LIST))))..)
endif
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
	GOROOT=${GIT_TOP}/go_1.19/go
else
	GOROOT=$(shell python -c 'import os.path; print(os.path.realpath("/usr/local/bin/go").rstrip("/bin/go"))')
endif
ROOT=${GIT_TOP}
GOPATH=${GIT_TOP}


export ROOT
export GOROOT
export GOPATH
export GOROOT_BOOTSTRAP
