GIT_TOP=$(shell git rev-parse --show-toplevel 2>/dev/null)
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
	GOROOT=${GIT_TOP}/go_1.19/go
else
	GOROOT=$(shell python -c 'import os.path; print(os.path.realpath("/usr/local/bin/go").rstrip("/bin/go"))')
endif
ROOT=${GIT_TOP}
GOPATH=${GIT_TOP}


export ROOT
export GOROOT
export GOPATH
export GOROOT_BOOTSTRAP
